language: python

cache: pip
sudo: required
dist: xenial

python:
  - "2.7"
  - "3.5"

addons:
  apt:
    packages:
      - xvfb

install:
  - pip install coveralls pytest flake8
  - pip install scipy
  - python setup.py -q install
  - pip install numpy
  - pip install matplotlib

before_script:
  - export DISPLAY=:'99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

script:
    - coverage run --source=acc setup.py test

after_script:
  - flake8 acc

after_success:
  - coveralls
